# Generated by Django 2.2.4 on 2019-10-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=50)),
                ('log', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('searchTerm', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweetId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fullText', models.CharField(max_length=400)),
                ('userId', models.CharField(max_length=60)),
                ('sentiment', models.DecimalField(decimal_places=3, max_digits=4)),
                ('date', models.DateTimeField()),
                ('likes', models.PositiveIntegerField()),
                ('retweets', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('tweetId', models.ManyToManyField(to='Twitter.Tweet')),
            ],
        ),
    ]
