# Generated by Django 2.2.4 on 2019-09-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='date',
        ),
    ]
