# Generated by Django 2.2.4 on 2019-09-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0002_remove_tweet_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweets',
        ),
    ]
