# Generated by Django 2.2.4 on 2019-10-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0003_auto_20191022_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlist',
            name='tweetId',
        ),
    ]
