# Generated by Django 2.2.5 on 2019-09-18 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0003_auto_20190911_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='sentiment',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField()),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Twitter.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Twitter.Tweet')),
            ],
        ),
    ]
